#!/command/with-contenv bash

# Exit on error
set -e

# Check to see if the bioman CLI exists and assume it means bioman is configured
if [ -f $APP_BASE_DIR/bioman ] && [ ${AUTORUN_ENABLED:="true"} == "true" ]; then
        echo "🏃‍♂️ Checking for automations..."

        ############################################################################
        # Automated database upgrade
        ############################################################################
        if [ ${AUTORUN_BIOMAN_DATABASE_UPGRADE:="true"} == "true" ]; then
            echo "🚀 Running database upgrade..."
            php $APP_BASE_DIR/bioman migrate
        fi

else
    echo "👉 Skipping automations because we could not detect a bioman install or it was specifically disabled..."
fi

exit 0
